version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - ./build production
  post_build:
    commands:
      - printf '{"ImageURI":"%s"}' 584009860414.dkr.ecr.ca-central-1.amazonaws.com/production/websocket-api:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - taskDef.json
    - appspec-production.yaml
