version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - ./build dev
  post_build:
    commands:
      - printf '{"ImageURI":"%s"}' 584009860414.dkr.ecr.ca-central-1.amazonaws.com/dev/websocket-api:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - taskDef.json
    - build-files/appspec-dev.yaml
